language: php

php:
  - 7.1

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  # check coding standard (defined in composer.json "scripts" section)
  # if this fails, run "composer fix-cs" to fix all fixable issues
  - composer check-cs

after_script:
  # upload coverage to Coveralls.io
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose

notifications:
  email: never
