language: php

php:
  - 7.2
  - 7.1

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
  - phpenv config-rm xdebug.ini || return 0
  - composer check-cs

after_script:
  # upload coverage to Coveralls.io
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: never
